# Generated by Django 3.2.6 on 2021-09-02 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_demo', '0002_auto_20210902_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 9, 2, 17, 48, 8, 543176)),
            preserve_default=False,
        ),
    ]
